import { GradingAssignment, Mastery, Submission } from "./types";

export const assignments: GradingAssignment[] = [
 {id:"variables",title:"The Tip Splitter",description:"Read a bill total and a positive number of people, then print each person's equal share rounded to exactly two decimal places.",starterCode:'bill = float(input())\npeople = int(input())\n\n# Calculate and print each person\'s share\n',difficulty:"Beginner",skill:"variables",tests:[{input:"100\n4",expected:"25.00"},{input:"99\n3",expected:"33.00"}],hiddenTests:[{input:"10\n2",expected:"5.00"},{input:"0\n5",expected:"0.00"},{input:"87.5\n5",expected:"17.50"},{input:"1\n8",expected:"0.12"}],rubric:"Read both inputs, divide the bill by the number of people, and print only the share formatted to exactly two decimal places. Handle zero and decimal bill totals without hardcoding cases.",referenceSolution:'bill = float(input())\npeople = int(input())\nprint(f"{bill / people:.2f}")'},
 {id:"conditionals",title:"Ticket Booth",description:"Read an age. Print child for age under 13, teen for age 13 through 19 inclusive, and adult for age 20 or older.",starterCode:'age = int(input())\n\n# Print the correct ticket category\n',difficulty:"Beginner",skill:"conditionals",tests:[{input:"12",expected:"child"},{input:"13",expected:"teen"}],hiddenTests:[{input:"0",expected:"child"},{input:"19",expected:"teen"},{input:"20",expected:"adult"},{input:"65",expected:"adult"}],rubric:"Read one integer age and print exactly child, teen, or adult using the stated boundaries: age < 13, 13 <= age <= 19, and age >= 20. Boundary values must be correct.",referenceSolution:'age = int(input())\nif age < 13:\n    print("child")\nelif age <= 19:\n    print("teen")\nelse:\n    print("adult")'},
 {id:"loops",title:"Fizz Counter",description:"Read a non-negative integer n and use a loop to print the sum of every integer from 1 through n. For n = 0, print 0.",starterCode:'n = int(input())\n\n# Use a loop to calculate the total\n',difficulty:"Beginner",skill:"loops",tests:[{input:"5",expected:"15"},{input:"1",expected:"1"}],hiddenTests:[{input:"10",expected:"55"},{input:"0",expected:"0"},{input:"2",expected:"3"},{input:"100",expected:"5050"}],rubric:"Read n, initialize an accumulator, use iteration to add every integer from 1 through n inclusively, and print only the total. The zero case must produce 0.",referenceSolution:'n = int(input())\ntotal = 0\nfor value in range(1, n + 1):\n    total += value\nprint(total)'},
 {id:"lists",title:"Above Average",description:"Read one non-empty line of space-separated integers and print how many values are strictly greater than the list's arithmetic average.",starterCode:'numbers = list(map(int, input().split()))\n\n# Count values above the average\n',difficulty:"Intermediate",skill:"lists",tests:[{input:"1 2 3 4 5",expected:"2"},{input:"10 10 10",expected:"0"}],hiddenTests:[{input:"1 100 101",expected:"2"},{input:"-1 0 1",expected:"1"},{input:"5",expected:"0"},{input:"-5 -1 -3",expected:"1"}],rubric:"Parse all integers into a list, compute their arithmetic average, count values strictly greater than that average, and print only the count. Equal-to-average values do not count; negative values and a single-item list must work.",referenceSolution:'numbers = list(map(int, input().split()))\naverage = sum(numbers) / len(numbers)\nprint(sum(1 for number in numbers if number > average))'},
 {id:"functions",title:"Palindrome Lab",description:"Implement is_palindrome(text), then read one line and print True or False. Ignore letter case, spaces, and punctuation; an empty string is a palindrome.",starterCode:'def is_palindrome(text):\n    # Return whether text reads the same backwards\n    pass\n\ntext = input()\nprint(is_palindrome(text))\n',difficulty:"Intermediate",skill:"functions",tests:[{input:"Racecar",expected:"True"},{input:"hello",expected:"False"}],hiddenTests:[{input:"A man a plan a canal Panama",expected:"True"},{input:"",expected:"True"},{input:"12321",expected:"True"},{input:"No lemon, no melon!",expected:"True"}],rubric:"Define and call is_palindrome(text). Normalize by ignoring case and non-alphanumeric characters, compare the normalized text with its reverse, return a boolean, and print that boolean. Empty normalized text returns True.",referenceSolution:'def is_palindrome(text):\n    normalized = "".join(char.lower() for char in text if char.isalnum())\n    return normalized == normalized[::-1]\n\ntext = input()\nprint(is_palindrome(text))'}
];

export const demoMastery: Mastery = {variables:.82,conditionals:.68,loops:.44,lists:.31,functions:.25};
export const demoSubmissions: Submission[] = [
 {id:"s1",studentId:"demo-student",studentName:"Maya Chen",assignmentId:"variables",assignmentTitle:"The Tip Splitter",skill:"variables",grade:100,feedback:"All tests passed.",submittedAt:"2026-06-30T09:42:00Z"},
 {id:"s2",studentId:"student-2",studentName:"Noah Williams",assignmentId:"loops",assignmentTitle:"Fizz Counter",skill:"loops",grade:50,feedback:"1 of 2 tests passed.",submittedAt:"2026-06-30T08:15:00Z"},
 {id:"s3",studentId:"demo-student",studentName:"Maya Chen",assignmentId:"conditionals",assignmentTitle:"Ticket Booth",skill:"conditionals",grade:100,feedback:"All tests passed.",submittedAt:"2026-06-29T14:06:00Z"}
];
